### ISSUE TITLE
Browser receiving Access-Control-Allow-Origin:* instead of actual values

### ISSUE THREAD

**Issue by Ejaboneta** [asm89/stack-cors#47]
I have to admit I don't fully understand how this is supposed to work but I have been having trouble with setting Access-Control-Allow-Origin on my Drupal site. This is my configuration:

```
  cors.config:
    enabled: true
    allowedHeaders: ['x-csrf-token','authorization','content-type','allow','origin','x-requested-with']
    allowedMethods: ['*']
    allowedOrigins: ['http://localhost:3000']
    exposedHeaders: false
    maxAge: false
    supportsCredentials: true

```
The response I get shows:
`Access-Control-Allow-Origin: *`

At first I thought it was using '*' and not  'http://localhost:3000'. I tried changing the allowed origin to a fake host, just to test, and it didn't work so I know that it is actually using 'http://localhost:3000' instead of '*'.  The problem for me is when I try to use 'include' for credentials, I get the following response:

`Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access.`
